

server:
  port: 0

spring:
  application:
    name: catalog-service
  h2:
    ## ???:????/h2-console???? db?? ??.
    ##jdbc:h2:mem:testdb
    ## id: sa
    ## pw: ??
    ## ? ??
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    ## ???, ??? init? ?? ???
    ## https://milenote.tistory.com/70
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
#    username: sa
#    password: 1234

eureka:
  instance:
    #????? ??? ??
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.example.catalogservice: DEBUG
